apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: backend-pull-request

  annotations:
    pipelinesascode.tekton.dev/max-keep-runs: "5"
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/task: git-clone

spec:
  taskRunTemplate:
    serviceAccountName: pipeline

  pipelineRef:
    name: backend-pipeline

  params:
    - name: repo-url
      value: "{{ repo_url }}"

    - name: revision
      value: "{{ revision }}"

    - name: deploy
      value: "false"

  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce

          resources:
            requests:
              storage: 1Gi

    - name: basic-auth
      secret:
        secretName: "{{ git_auth_secret }}"